name: Build
on:
  - pull_request
  - push
permissions:
  contents: write
  packages: write
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tag
        id: tags
        run: |
          echo "docker_registry=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"
          echo "tag=$(date --iso-8601)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: base
          platforms: linux/amd64
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }} # Only push on main branch
          tags: ${{ steps.tags.outputs.docker_registry }}/base:${{ steps.tags.outputs.tag }},${{ steps.tags.outputs.docker_registry }}/base:latest # Create latest + date tags
